@SelfMade.Api_HostAddress = http://localhost:5221

### Получить совет от ИИ за сегодняшний день
GET {{SelfMade.Api_HostAddress}}/api/analytics/daily/1
Accept: application/json

### Регистрация нового пользователя (Проверка шифрования)
POST {{SelfMade.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "SuperUser",
  "email": "test2@mail.com",
  "password": "123"
}

###

### Вход в систему (Проверка логина)
POST {{SelfMade.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test2@mail.com",
  "password": "123"
}